### ISSUE TITLE
nginx config for serving static content lacks special case for serving packages assets

### ISSUE THREAD

**Issue by saimeunt** [yauh/meteor-benchapp#1]
In a Meteor app, packages assets are not located inside `app/programs/web.browser/app`, they live instead inside `app/programs/web.browser/packages/my-package`.

These packages assets URL are thus `http://www.domain.com/packages/my-package/image.png` and we need a nginx special location to serve them appropriately, I've added this directive at https://github.com/yauh/meteor-benchapp/blob/master/config/meteorServeStatic.conf#L41 :

```
location ^~ /packages {
  # this should point at the content from the app folder
  root /opt/carrusel/app/programs/web.browser;
  access_log off;
  expires 30d;
  add_header Pragma public;
  add_header Cache-Control "public";
}
```

This solved the problem for me, but I'm no nginx guru so you better double check that.

Thanks for the article BTW, using your nginx config as boilerplate from now on.

**Comment by yauh** [comment]
Thanks, excellent remark. Not sure why those packages slipped my mind for so long.

**Comment by saimeunt** [comment]
Noticed I forgot to replace `carrusel` (project of mine) with the example `meteor` in the code snippet I gave you !

https://github.com/yauh/meteor-benchapp/blob/master/config/meteorServeStatic.conf#L54

**Comment by yauh** [comment]
That's what I got from copying config all around three editors. Did a test run before applying the change, but copy paste always has a surprise for you I guess

Will change this to meteor soon. :-)

Typed on a tiny keyboard.
